# Generated by Django 3.0.5 on 2020-04-26 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200426_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='polarity',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customers',
            name='subjectivity',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customers',
            name='links',
            field=models.CharField(default='https://www.wikipedia.org/', max_length=500),
        ),
    ]
